// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO3rm3ZCtY-D-1QmbmXh-1ukpaVqwKCJw',
    appId: '1:1041628762058:web:2371ff6ab58403462a4933',
    messagingSenderId: '1041628762058',
    projectId: 'lookbook-19db7',
    authDomain: 'lookbook-19db7.firebaseapp.com',
    databaseURL: 'https://lookbook-19db7-default-rtdb.firebaseio.com',
    storageBucket: 'lookbook-19db7.appspot.com',
    measurementId: 'G-ZR7WC5GFZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9inmVeOPkA_IzvGCVC-N4aeApSuro3KM',
    appId: '1:1041628762058:android:5f25d84a559bf79d2a4933',
    messagingSenderId: '1041628762058',
    projectId: 'lookbook-19db7',
    databaseURL: 'https://lookbook-19db7-default-rtdb.firebaseio.com',
    storageBucket: 'lookbook-19db7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoa6om78ll4WSbQP1o4UJ5zXaWHhb14xM',
    appId: '1:1041628762058:ios:416808ed2a20b7782a4933',
    messagingSenderId: '1041628762058',
    projectId: 'lookbook-19db7',
    databaseURL: 'https://lookbook-19db7-default-rtdb.firebaseio.com',
    storageBucket: 'lookbook-19db7.appspot.com',
    iosClientId: '1041628762058-3t8arar980t3hgr25eujojssttqdg1g3.apps.googleusercontent.com',
    iosBundleId: 'com.example.lookbookbackend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoa6om78ll4WSbQP1o4UJ5zXaWHhb14xM',
    appId: '1:1041628762058:ios:416808ed2a20b7782a4933',
    messagingSenderId: '1041628762058',
    projectId: 'lookbook-19db7',
    databaseURL: 'https://lookbook-19db7-default-rtdb.firebaseio.com',
    storageBucket: 'lookbook-19db7.appspot.com',
    iosClientId: '1041628762058-3t8arar980t3hgr25eujojssttqdg1g3.apps.googleusercontent.com',
    iosBundleId: 'com.example.lookbookbackend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBO3rm3ZCtY-D-1QmbmXh-1ukpaVqwKCJw',
    appId: '1:1041628762058:web:be4280e8fedbd3122a4933',
    messagingSenderId: '1041628762058',
    projectId: 'lookbook-19db7',
    authDomain: 'lookbook-19db7.firebaseapp.com',
    databaseURL: 'https://lookbook-19db7-default-rtdb.firebaseio.com',
    storageBucket: 'lookbook-19db7.appspot.com',
    measurementId: 'G-Q3ZZRYHETM',
  );
}
